---
title: "Working Papers"
---

<style>
.pub-title {
  font-size: 120%;
  font-weight: bold;
}
body {
  font-size: 190%;
}
</style>

<style>
details.abstract {
  margin-top: 0.25rem;
  margin-bottom: 1rem;
}

details.abstract summary {
  cursor: pointer;
  font-weight: 600;
  list-style: none;
}

details.abstract summary::-webkit-details-marker {
  display: none; /* hide default triangle in some browsers */
}

details.abstract summary::before {
  content: "► ";
  font-size: 0.9em;
}

details.abstract[open] summary::before {
  content: "▼ ";
}

details.abstract {
  margin-top: -0.65em;    /* vertical space above */
  margin-bottom: 1em;   /* vertical space below */
}
</style>


<br>

1. <span class="pub-title">Artificial Intelligence and the Labor Market</span>     
(*with [Menaka Hampole](https://www.menakahampole.com/), [Lawrence Schmidt](https://sites.google.com/site/lawrencedwschmidt/home), and [Bryan Seegmiller](https://mitsloan.mit.edu/phd/students/bryan-seegmiller)*)  
   *Quarterly Journal of Economics, Revise and Resubmit*   
   [[Paper](https://www.dropbox.com/scl/fi/t0o23d6wc5e20q4z9fv2k/AILabor.pdf?rlkey=odaafoy773d8xgpxn1nwt3900&raw=1) (ver. 9/2025)]
<details class="abstract">
  <summary>Summary</summary>
  We leverage recent advances in NLP to construct measures of workers' task exposure to AI and machine learning technologies over the 2010 to 2023 period that vary across firms and time. Using a theoretical framework that allows for a labor-saving technology to affect worker productivity both directly and indirectly, we show that the impact on wage earnings and employment can be summarized by two statistics. First, labor demand decreases in the average exposure of workers' tasks to AI technologies; second, holding the average exposure constant, labor demand increases in the dispersion of task exposures to AI, as workers shift effort to tasks that are not displaced by AI. Exploiting exogenous variation in our measures based on pre-existing hiring practices across firms, we find empirical support for these predictions, together with a lower demand for skills affected by AI. Overall, we find muted effects of AI on employment due to offsetting effects: highly-exposed occupations experience relatively lower demand compared to less exposed occupations, but the resulting increase in firm productivity increases overall employment across all occupations.  
</details>

   
 
   

1. <span class="pub-title">Measuring Creative Destruction</span>     
(*with [Ali Kakhbod](https://haas.berkeley.edu/faculty/ali-kakhbod/), [Leonid Kogan](http://web.mit.edu/lkogan2/www/), and Peiyao Li*)    
   *Review of Financial Studies, Revise and Resubmit*   
   [[Paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5008685) (ver. 2/2025)]
<details class="abstract">
  <summary>Summary</summary>
  We examine the link between a firm's future performance and innovations made by other firms using text-based measures of innovation displacement—how relevant one firm's innovations are to another's operations. Our findings indicate that when other major innovators' recent innovations are similar to the focal firm's technologies, the focal firm's profit growth over the next 7 years is expected to decline, with the association exacerbating annually, especially for non-innovative firms. This displacement effect persists across various firm types and model specifications. Moreover, firms exposed to higher displacement have higher risk-adjusted stock returns in the following year. 
</details>

 

1. <span class="pub-title">Technology and Labor Displacement: Evidence from Linking Patents with Worker-Level Data</span>    
(*with [Leonid Kogan](http://web.mit.edu/lkogan2/www/), [Lawrence Schmidt](https://sites.google.com/site/lawrencedwschmidt/home), and [Bryan Seegmiller](https://mitsloan.mit.edu/phd/students/bryan-seegmiller)*)  
   *Review of Economic Studies, Revise and Resubmit*   
   [[Paper](https://www.dropbox.com/scl/fi/zlq7u209oirvvs0r3nmdi/LaborDisplacement_RNR.pdf?rlkey=6fq1m25o366f9r0iwoiz0cfi7&raw=1) (ver. 7/2024)]
   [[Slides](https://www.dropbox.com/scl/fi/q9t5e5bqbw1rg9rab0vfv/LaborDisplacement_RNR_Slides.pdf?rlkey=6rycbz7u4dzu3g5guse5vfu4z&raw=1)]
<details class="abstract">
  <summary>Summary</summary>   We develop separate measures of workers' exposure to labor-saving and labor-augmenting technologies based on textual analysis of patent documents and the tasks performed by workers in an occupation. Using administrative data on earnings of individual workers in the US, we show that these exposure measures are both negatively related to earnings of incumbent workers. Exposure to labor-saving technologies is associated with significant declines in average earnings and a higher likelihood of job loss for all worker types. By contrast, exposure to labor-augmenting technologies is associated with earnings declines for only certain types of workers: white collar workers, older workers, and workers that are paid more relative to their peers. In contrast to these effects on incumbents, we find a positive overall effect of labor-augmenting technologies on total worker compensation, employment, and the labor share. We interpret the sign and magnitudes of these effects through a model that also allows for skill displacement.  
</details>

1. <span class="pub-title">Productivity Shocks and Inflation in Incomplete Markets</span>     
(*with [Qiushi Huang](https://en.saif.sjtu.edu.cn/faculty-research/huang-qiushi) and [Leonid Kogan](http://web.mit.edu/lkogan2/www/)*)  
   *Review of Financial Studies, Revise and Resubmit*   
   [[Paper](https://www.dropbox.com/scl/fi/k3ozsygbvlpedk4bhk4hy/InflationRiskSharing.pdf?rlkey=i1de4xrobgfgzto6ggxlau5hs&raw=1) (ver. 5/2025)]

   <details class="abstract">
  <summary>Summary</summary>  Innovation leads to higher productivity, yet it can lead to higher inflation if markets are incomplete. Exploiting changes in state-level R\&D tax credit policy, we establish a causal link between the level of innovation and the local price of non-tradable consumption goods. We rationalize this finding in a multi-region model of a monetary union where regions can experience displacive shocks that reallocate output among agents. Because benefits of economic growth accrue asymmetrically across all agents, prices of non-tradable goods can rise even as regional output increases. Local stock markets provide evidence that is consistent with model predictions. In both the data and the model, returns to local growth firms help agents insure against increases in the local price level.  </details>


1. <span class="pub-title">Intangible Capital, Firm Scope, and Growth</span>     
(*with [Nicolas Crouzet](https://www.kellogg.northwestern.edu/faculty/crouzet/html/index.html), [Janice Eberly](https://www.kellogg.northwestern.edu/faculty/directory/eberly_janice_c.aspx), and [Andrea Eisfeldt](http://www.anderson.ucla.edu/x33175.xml)*)   
   [[Paper](https://www.dropbox.com/s/t3pun2wpakqbz55/ceep_latest.pdf?raw=1) (ver. 9/2024)]
   <details class="abstract">
  <summary>Summary</summary>  Intangible assets represent information that needs to be embodied, or stored, in order to be used in production. This information can be replicated and stored in multiple instances, even if imperfectly. Replicability implies that a specific intangible asset can be deployed simultaneously in multiple uses by a single firm, allowing it to expand its scope. At the same time, however, replicability implies a risk that a firm's intangibles will be copied or appropriated by competitors. We embed these properties into an otherwise standard endogenous growth model, and show how improvements in the technology for replicating intangibles can lead to larger firms, an increase in concentration, valuation ratios, and the profit share, but lower growth.  </details>

   
1. <span class="pub-title">Tech Dollars: Technological Innovation and Exchange Rates</span>   
   (*with [Qiushi Huang](https://en.saif.sjtu.edu.cn/faculty-research/huang-qiushi) and [Leonid Kogan](http://web.mit.edu/lkogan2/www/)*)   
   [[Paper](https://www.dropbox.com/scl/fi/ovcv0ibcyi34eiyguwtgl/FX_techdollars.pdf?rlkey=nhjtfvg1met7cfx46hmova6sb&raw=1) (ver. 09/2025)]
<details class="abstract">
  <summary>Summary</summary>  We document that there is a (re)connection between exchange rate movements and relative changes in aggregate quantities, such as consumption and output growth, once wealth changes are controlled for. We find that relative wealth changes positively correlate with aggregate quantities, and that the real dollar index is positively correlated with U.S. innovation intensity. These observations motivate our analysis of how technological innovation affects exchange rate movements. We introduce a minimal deviation from the standard endowment economy model of exchange rate: in an economic boom, new firms are created, but they are randomly distributed to a small part of the population. Our calibrated model successfully replicates key features of the data, specifically, the joint dynamics of exchange rates, stock returns, real output and consumption growth, and trade flows.  </details>



1. <span class="pub-title">Evaluation and Learning in R\&D Investment</span>    
(*with [Alex Frankel](https://faculty.chicagobooth.edu/alexander-frankel), [Danielle Li](https://mitsloan.mit.edu/faculty/directory/danielle-li), and [Joshua Krieger](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=951435)*)  
   *Management Science, Revise and Resubmit*  
   *Winner of the 2025 Red Rock Conference Best Paper Award*  
   [[Paper](https://www.dropbox.com/s/i18l4ghq06oq82f/evaluation_learning.pdf?raw=1) (ver. 1/2025)]
   <details class="abstract">
  <summary>Summary</summary>  We examine the role of spillover learning in shaping the value of exploratory versus incremental R\&D. Using data from drug development, we show that novel drug candidates generate more knowledge spillovers than incremental ones. Despite being less likely to reach regulatory approval, they are more likely to inspire subsequent successful drugs. We introduce a model where firms are better able to *evaluate* the viability of incremental drugs, but where investing in novel drugs helps firms *learn* about future projects. Firms appear to put more value on evaluation versus learning motives, and these patterns are in-part driven by the appropriability of new knowledge and firms' discount rates. </details> 

<br> 

## Dormant Working Papers
 

1. <span class="pub-title">Technological Innovation and Labor Income Risk</span>  
   (*with [Leonid Kogan](http://web.mit.edu/lkogan2/www/), [Lawrence Schmidt](https://sites.google.com/site/lawrencedwschmidt/home), and Jae Song*)   
   [[Paper](https://www.nber.org/papers/w26964)]
   
   <details class="abstract">
  <summary>Summary</summary>  Using administrative data, we examine how labor income risk depends on innovation shocks. Subsumed by “Winners and Losers: Competition, Creative Destruction, and Labor Income Risk.”</details>  

   

1. <span class="pub-title">Sources of Systematic Risk</span>  
   (*with Igor Makarov*)   
   [[Paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=968229)]
   <details class="abstract">
  <summary>Summary</summary>  Using the restrictions implied by the heteroskedasticity of stock returns, we identify four factors in the U.S. industry returns. The first correlates highly with the market portfolio; the second is a portfolio of stocks that produce investment goods minus stocks that produce consumption goods; the third differentiates between cyclical and noncyclical stocks. The fourth, a portfolio of industries that produce input goods minus the rest of the market, is a robust predictor of excess returns on the market portfolio and bond returns. The extracted factors are shown to contain significant information about future macroeconomic and financial variables.</details>    

   
